name = "etalenter-browser-worker"
main = "_worker.js"
compatibility_date = "2025-10-04"
compatibility_flags = ["nodejs_compat"]

# Pages configuration for Git repository integration
pages_build_output_dir = "./"

# Observability configuration for consistent logging across deployments
[observability.logs]
enabled = true

# Browser rendering binding
[browser]
binding = "MYBROWSER"

# KV namespace configuration
# Add your KV namespace IDs after creating them with:
# npx wrangler kv namespace create BROWSER_KV_DEMO
# npx wrangler kv namespace create BROWSER_KV_DEMO --preview
[[kv_namespaces]]
binding = "BROWSER_KV_DEMO"
id = "your-production-kv-id-here"
preview_id = "your-preview-kv-id-here"

# Build configuration optimized for Pages
[build]
command = "npm run pages:build"
cwd = "./"

# Functions configuration for Pages
[functions]
directory = "./"